### ISSUE TITLE
updatelayer raises exception on tabular data

### ISSUE THREAD

**Issue by ridoo** [GeoNodeUserGroup-DE/geonode-dev-datapackage#13]
[`updatelayers command`](https://docs.geonode.org/en/master/admin/mgmt_commands/index.html#management-command-updatelayers) raises on datasets which have `subtype=tabular`:

```
root@2fdce1e77dc2:/usr/src/geonode# python manage.py updatelayers
Inspecting the available layers in GeoServer ...
Found 2 layers, starting processing
WARNING Could not clean style for layer horizon_data
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/geoserver/helpers.py", line 1130, in clean_styles
    logger.debug(f'clean_styles: Retrieving style "{gs_dataset.default_style.name}" for cleanup')
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by ridoo** [comment]
After fixing some other issues, now I get (which could be related to https://github.com/GeoNodeUserGroup-DE/geonode-dev-datapackage/issues/18):

```
ERROR java.lang.NullPointerException
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/thumbs/utils.py", line 219, in get_map
    image = getmap(
  File "/usr/src/geonode/geonode/thumbs/utils.py", line 436, in getmap
    raise ServiceException(err_message)
owslib.util.ServiceException: java.lang.NullPointerException
ERROR java.lang.NullPointerException
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/thumbs/utils.py", line 219, in get_map
    image = getmap(
  File "/usr/src/geonode/geonode/thumbs/utils.py", line 436, in getmap
    raise ServiceException(err_message)
owslib.util.ServiceException: java.lang.NullPointerException
```

**Comment by ridoo** [comment]
We should consider to override `THUMBNAIL_GENERATOR = os.environ.get("THUMBNAIL_GENERATOR", "geonode.thumbs.thumbnails.create_gs_thumbnail_geonode")` and handle the `tabular` case. Do this in one go with #22.
